# -------------------------
# Gradle JVM et performance
# -------------------------
org.gradle.jvmargs=-Xmx4G -XX:MaxMetaspaceSize=1G -XX:+HeapDumpOnOutOfMemoryError
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.configureondemand=true

# -------------------------
# AndroidX & Jetifier
# -------------------------
android.useAndroidX=true
android.enableJetifier=true
